// Today Forecast
export const GET_TODAY_FORECAST_ATTEMPT = 'GET_TODAY_FORECAST_ATTEMPT';
export const GET_TODAY_FORECAST_SUCCESS = 'GET_TODAY_FORECAST_SUCCESS';
export const GET_TODAY_FORECAST_FAILURE = 'GET_TODAY_FORECAST_FAILURE';

// Five Days Forecast
export const GET_FIVE_DAYS_FORECAST_ATTEMPT = 'GET_FIVE_DAYS_FORECAST_ATTEMPT';
export const GET_FIVE_DAYS_FORECAST_SUCCESS = 'GET_FIVE_DAYS_FORECAST_SUCCESS';
export const GET_FIVE_DAYS_FORECAST_FAILURE = 'GET_FIVE_DAYS_FORECAST_FAILURE';
